### ISSUE TITLE
Be able to set language for a show

### ISSUE THREAD

**Issue by essoen** [Studentmediene/RadioRevolt-API#6]

**Comment by tobinus** [comment]
Only the two-letter codes in [ISO 639](http://www.loc.gov/standards/iso639-2/php/code_list.php) (possibly with modifiers, like `en-us`) are accepted by Itunes. The only ones relevant to us would be `en` for English and `no` for Norwegian. It is used to inform Itunes and other aggregators about what language the podcast is in, which changes where it appears, the Itunes store page and who it appears for.
